name: llm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.3
  - conda=23.5.0
  - pip=23.0.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pandas=2.0.2
  - scipy=1.10.1
  - pip:
    - transformers==4.29.2
    - tokenizers==0.13.3
    - huggingface-hub==0.15.1