name: foo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.3
  - conda=23.5.0
  - pip=23.0.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2