name: foo
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11.3
  - conda=23.5.0
  - pip=23.0.1
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.15.2
  - pytorch::torchaudio=2.0.2